name = "SymmetricSparseMatrices"
uuid = "05127f78-d533-11e9-247e-fd7d09ecf029"
authors = ["Víctor Sande Veiga", "International Centre for Numerical Methods in Engineering"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
